=== juankitavelita/Repositorion-t/actividad29/actividad29.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="rss">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="channel">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="link" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                            <xs:attribute name="href" />
                                            <xs:attribute name="rel" />
                                            <xs:attribute name="type" />
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="title" />
                            <xs:element name="language" type="xs:string" />
                            <xs:element name="pubDate" type="xs:string" />
                            <xs:element name="lastBuildDate" type="xs:string" />
                            <xs:element name="category" />
                            <xs:element name="docs" type="xs:string" />
                            <xs:element name="generator" type="xs:string" />
                            <xs:element name="item">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="title" />
                                        <xs:element name="link" type="xs:string" />
                                        <xs:element name="description" />
                                        <xs:element name="pubDate" type="xs:string" />
                                        <xs:element name="guid">
                                            <xs:complexType>
                                                <xs:simpleContent>
                                                    <xs:extension base="xs:string">
                                                        <xs:attribute name="isPermaLink"
                                                            type="xs:boolean" use="required" />
                                                    </xs:extension>
                                                </xs:simpleContent>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="category" type="xs:string" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="version" type="xs:decimal" use="required" />
        </xs:complexType>
    </xs:element>
</xs:schema>

=== juankitavelita/Repositorion-t/actividad29/actividad29.xml
<?xml-stylesheet href="actividad29.xsl" type="text/xsl"?>
<rss xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="actividad29.xsd" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:content="http://purl.org/rss/1.0/modules/content/" version="2.0">
    <channel>
    <atom:link href="http://todotelecinco.webnode.es/rss/noticias.xml" rel="self" type="application/rss+xml"/>
    <title>
    <![CDATA[ Noticias - todotelecinco.webnode.es ]]>
    </title>
    <link>http://todotelecinco.webnode.es</link>
    <language>es</language>
    <pubDate>Thu, 13 Dec 2012 18:18:00 +0100</pubDate>
    <lastBuildDate>Thu, 13 Dec 2012 18:18:00 +0100</lastBuildDate>
    <category>
    <![CDATA[ Noticias ]]>
    </category>
    <docs>http://blogs.law.harvard.edu/tech/rss</docs>
    <generator>Webnode</generator>
    <item>
    <title>
    <![CDATA[ Cancelada la gira de 'La Voz' que contaba con los ocho finalistas ]]>
    </title>
    <link>http://todotelecinco.webnode.es/news/cancelada-la-gira-de-la-voz-que-contaba-con-los-ocho-finalistas/</link>
    <description>
    <![CDATA[ Telecinco, Boomerang y Universal Music no se han pronunciado aún al respecto. &nbsp; &nbsp; La gira de 'La Voz' ha sido cancelada. Poco más se sabe al respecto, excepto que las páginas encargadas de la venta de entradas han retirado la posibilidad de disfrutar de los concursantes en vivo y en directo.&nbsp; &nbsp; Era cuestión de tiempo que Jesús Vázquez anunciase una gira de conciertos por todo el territorio nacional tras el éxito cosechado por el talent show musical. Concretamente... ]]>
    </description>
    <pubDate>Thu, 13 Dec 2012 18:18:00 +0100</pubDate>
    <guid isPermaLink="true">http://todotelecinco.webnode.es/news/cancelada-la-gira-de-la-voz-que-contaba-con-los-ocho-finalistas/</guid>
    <category>Noticias</category>
    </item>
    </channel>
    <channel>
        <atom:link href="http://todotelecinco.webnode.es/rss/noticias.xml" rel="self" type="application/rss+xml"/>
        <title>
        <![CDATA[ Noticias - todotelecinco.webnode.es ]]>
        </title>
        <link>http://todotelecinco.webnode.es</link>
        <language>es</language>
        <pubDate>Thu, 13 Dec 2012 18:18:00 +0100</pubDate>
        <lastBuildDate>Thu, 13 Dec 2012 18:18:00 +0100</lastBuildDate>
        <category>
        <![CDATA[ Noticias ]]>
        </category>
        <docs>http://blogs.law.harvard.edu/tech/rss</docs>
        <generator>Webnode</generator>
        <item>
        <title>
        <![CDATA[ Cancelada la gira de 'La Voz' que contaba con los ocho finalistas ]]>
        </title>
        <link>http://todotelecinco.webnode.es/news/cancelada-la-gira-de-la-voz-que-contaba-con-los-ocho-finalistas/</link>
        <description>
        <![CDATA[ Telecinco, Boomerang y Universal Music no se han pronunciado aún al respecto. &nbsp; &nbsp; La gira de 'La Voz' ha sido cancelada. Poco más se sabe al respecto, excepto que las páginas encargadas de la venta de entradas han retirado la posibilidad de disfrutar de los concursantes en vivo y en directo.&nbsp; &nbsp; Era cuestión de tiempo que Jesús Vázquez anunciase una gira de conciertos por todo el territorio nacional tras el éxito cosechado por el talent show musical. Concretamente... ]]>
        </description>
        <pubDate>Thu, 13 Dec 2012 18:18:00 +0100</pubDate>
        <guid isPermaLink="true">http://todotelecinco.webnode.es/news/cancelada-la-gira-de-la-voz-que-contaba-con-los-ocho-finalistas/</guid>
        <category>Noticias</category>
        </item>
        </channel>
</rss>
