=== juankitavelita/Repositorion-t/actividad17/actividad17_externo.dtd
<!ELEMENT lista_de_notas (nota+)>
    <!ELEMENT nota (para, de, titulo, contenido)>
    <!ATTLIST nota dia CDATA #IMPLIED>
    <!ATTLIST nota hora CDATA #IMPLIED>
    <!ELEMENT para (#PCDATA)>
    <!ELEMENT de (#PCDATA)>
    <!ELEMENT titulo (#PCDATA)>
    <!ELEMENT contenido (#PCDATA)>

=== juankitavelita/Repositorion-t/actividad17/actividad17_externo.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE lista_de_notas SYSTEM "actividad17_externo.dtd">
<lista_de_notas>
    <nota>
        <para>Pedro</para>
        <de>Laura</de>
        <titulo>Recordatorio</titulo>
        <contenido>A las 7:00 pm en la puerta del teatro </contenido>
    </nota>
    <nota dia="23/01/2010" hora="13:15"> 
        <para>Miguel</para> 
        <de>Juan</de> 
        <titulo>Informes</titulo> 
        <contenido>Te he dejado los informes en el casillero</contenido> 
    </nota> 
</lista_de_notas>
