=== juankitavelita/Repositorion-t/XML/actividad20/actividad20.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="matricula">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="personal">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="dni" type="xs:string"></xs:element>
                            <xs:element name="nombre" type="xs:string"></xs:element>
                            <xs:element name="titulacion" type="xs:string"></xs:element>
                            <xs:element name="curso_academico" type="xs:string"></xs:element>
                            <xs:element name="domicilios">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="domicilio" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="nombre" type="xs:string"></xs:element>
                                                </xs:sequence>
                                                <xs:attribute name="tipo" use="required"></xs:attribute>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="pago">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="tipo_matricula" type="xs:string"></xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== juankitavelita/Repositorion-t/XML/actividad20.xml
<?xml version="1.0"  encoding="ISO-8859-1"?> 
<matricula xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="actividad20.xsd"> 
    <personal> 
        <dni>99223366M</dni> 
        <nombre>Juan Pardo Martín</nombre> 
        <titulacion>Ingeniería Informática</titulacion> 
       <curso_academico>1997/1998</curso_academico> 
       <domicilios> 
           <domicilio tipo="familiar"> 
               <nombre>C/ Principal nº1</nombre> 
           </domicilio> 
            <domicilio tipo="habitual"> 
                <nombre>C/ Secundaria nº2</nombre> 
            </domicilio> 
        </domicilios> 
    </personal> 
    <pago>
        <tipo_matricula>Matrícula Ordinaria</tipo_matricula>
    </pago>
</matricula>
