<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE factura [
    <!ELEMENT factura (datos_empresa, datos_cliente, datos_factura)>
    <!ATTLIST factura n_fac CDATA ID #REQUIRED>
    <!ELEMENT datos_empresa (nombre, dir, poblacion, provincia, cif, telefono*)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT dir (#PCDATA)>
    <!ELEMENT poblacion (#PCDATA)>
    <!ATTLIST poblacion cod_postal CDATA #IMPLIED>
    <!ELEMENT provincia (#PCDATA)>
    <!ELEMENT cif (#PCDATA)>
    <!ELEMENT telefono (#PCDATA)>
    <!ATTLIST telefono telefono #FIXED "917776688">
    <!ATTLIST telefono fax #FIXED "917776699">
    <!ELEMENT datos_cliente (nombre, dir_env, poblacion, provincia)>
    <!ATTLIST datos_cliente n_clic CDATA ID #REQUIRED>
    <!ELEMENT dir_env (#PCDATA)>
    <!ELEMENT datos_factura (fecha, linea+, base, cuota_iva, total)>
    <!ATTLIST datos_factura n_ped CDATA #IMPLIED>
    <!ATTLIST datos_factura iva CDATA NMTOKEN #REQUIRED>
    <!ATTLIST datos_factura f_pago CDATA (efectivo | tarjeta | plazos) "efectivo" #REQUIRED>
    <!ATTLIST datos_factura moneda CDATA "euro" #FIXED>
    <!ELEMENT fecha (#PCDATA)>
    <!ELEMENT linea (ref, desc, cant, precio, importe)>
    <!ELEMENT ref (#PCDATA)>
    <!ELEMENT desc (#PCDATA)>
    <!ELEMENT cant (#PCDATA)>
    <!ELEMENT precio (#PCDATA)>
    <!ELEMENT importe (#PCDATA)>
    <!ELEMENT base (#PCDATA)>
    <!ELEMENT cuota_iva (#PCDATA)>
    <!ELEMENT total (#PCDATA)>
]>
<factura n_fac="f999"> 
    <datos_empresa> 
        <nombre>Equipos Digitales S.L.</nombre> 
        <dir>Av. Valladolid</dir> 
        <poblacion cod_postal="28043">Madrid</poblacion> 
        <provincia>Madrid</provincia> 
        <cif>Q-9876543</cif> 
        <telefono/> 
    </datos_empresa> 
    <datos_cliente n_cli="c879"> 
        <nombre>Darío, Bueno Gutiérrez</nombre> 
        <dir_env>Av. Oporto nº7 4ºd</dir_env> 
        <poblacion cod_postal="28043">Madrid</poblacion> 
        <provincia>Madrid</provincia> 
    </datos_cliente> 
    <datos_factura n_ped="p731" iva="16" f_pago= "efectivo" moneda="euro"> 
        <fecha>12-01-2005</fecha> 
        <linea> 
            <ref>MII93000F/8</ref> 
            <desc>MICRO PENTIUM IV 3000MHZ FB800</desc> 
            <cant>1</cant> 
            <precio>230</precio> 
            <importe>266,80</importe> 
        </linea> 
        <linea> 
            <ref>MB8QDIP4</ref> 
            <desc>PLACA BASE QDI P4</desc> 
            <cant>1</cant> 
            <precio>180</precio> 
            <importe>208,80</importe> 
        </linea> 
        <linea> 
            <ref>MEDD512M32</ref> 
            <desc>DIMM DDR 512MB 3200</desc> 
            <cant>2</cant> 
            <precio>40</precio> 
            <importe>92,80</importe> 
        </linea> 
        <linea> 
            <ref>HD250GSA7</ref> 
            <desc>DISCO DURO 250GB S-ATA 7200</desc> 
            <cant>4</cant> 
            <precio>120</precio> 
            <importe>556,80</importe> 
        </linea> 
        <base>970,00</base> 
        <cuota_iva>155,20</cuota_iva>
        <total>1125,20</total> 
    </datos_factura>
</factura>