=== juankitavelita/Repositorion-t/XML/actividad19/actividad19.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="lista_de_notas">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="nota" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="para" type="xs:string"></xs:element>
                            <xs:element name="de" type="xs:string"></xs:element>
                            <xs:element name="titulo" type="xs:string"></xs:element>
                            <xs:element name="contenido" type="xs:string"></xs:element>
                        </xs:sequence>
                        <xs:attribute name="dia" type="xs:date"></xs:attribute>
                        <xs:attribute name="hora"></xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== juankitavelita/Repositorion-t/XML/actividad19/actividad19.xml
<?xml version="1.0" encoding="UTF-8"?>
<lista_de_notas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="actividad19.xsd">
    <nota>
        <para>Pedro</para>
        <de>Laura</de>
        <titulo>Recordatorio</titulo>
        <contenido>A las 7:00 pm en la puerta del teatro </contenido>
    </nota>
    <nota dia="2010-01-23" hora="13:15:00">
        <para>Miguel</para>
        <de>Juan</de>
        <titulo>Informes</titulo>
        <contenido>Te he dejado los informes en el casillero</contenido>
    </nota>
</lista_de_notas>
